AWSTemplateFormatVersion: 2010-09-09
Description: Deploy application stack example in a basic VPC
Parameters:
  ProjectName:
    Description: A descriptive label used in Name tags
    Type: String
    Default: ''
  NotificationEmail:
    Description: Notification email for security events
    Type: String
  ProductionVpcCidrBlock:
    Description: Class B VPC Network CIDR, First two octets
    Type: String
    Default: '10.100'
  StagingVpcCidrBlock:
    Description: Class B VPC Network CIDR, First two octets
    Type: String
    Default: '10.101'
  TestVpcCidrBlock:
    Description: Class B VPC Network CIDR, First two octets
    Type: String
    Default: '10.102'
  DevelopmentVpcCidrBlock:
    Description: Class B VPC Network CIDR, First two octets
    Type: String
    Default: '10.103'
  ManagementVpcCidrBlock:
    Description: Class B VPC Network CIDR, First two octets
    Type: String
    Default: '10.10'
  AvailabilityZone1:
    Description: Availability Zone 1 Name in Region
    Type: AWS::EC2::AvailabilityZone::Name
  AvailabilityZone2:
    Description: Availability Zone 2 Name in Region
    Type: AWS::EC2::AvailabilityZone::Name
  StackTemplates:
    Description: Template service base URL
    Type: String
    Default: https://s3.us-east-2.amazonaws.com/cfn-stacks.com/templates
  InfraTemplates:
    Description: Key name prefix for infrastructure templates
    Type: String
    Default: release/com/amazon/aws/cfn-compliance-common/0.0.3
  bCreateProductionVPC:
    Description: Should the Production VPC get created?
    Type: String
    Default: true
  bCreateStagingVPC:
    Description: Should the Staging VPC get created?
    Type: String
    Default: true
  bCreateTestVPC:
    Description: Should the Test VPC get created?
    Type: String
    Default: true
  bCreateDevVPC:
    Description: Should the Dev VPC get created?
    Type: String
    Default: true
  allowedCIDR:
    Description: IPs allowed to access the bastion
    Type: String
  pEC2KeyPairBastion:
    Description: The SSH key pair in your account to use for the bastion host login
    Type: AWS::EC2::KeyPair::KeyName
  pEC2KeyPair:
    Description: The SSH key pair in your account to use for all other EC2 instance
      logins
    Type: AWS::EC2::KeyPair::KeyName
Conditions:
  CreateProductionVPC: !Equals [ true, !Ref bCreateProductionVPC]
  CreateStagingVPC: !Equals [ true, !Ref bCreateStagingVPC]
  CreateTestVPC: !Equals [ true, !Ref bCreateTestVPC]
  CreateDevVPC: !Equals [ true, !Ref bCreateDevVPC]
  LoadConfigRulesTemplate: !Equals [ true, !FindInMap [ RegionServiceSupport, !Ref 'AWS::Region', ConfigRules ] ]
Resources:
  IamTemplate:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub '${StackTemplates}/${InfraTemplates}/iam.yaml'
      TimeoutInMinutes: 20
  LoggingTemplate:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub '${StackTemplates}/${InfraTemplates}/logging.yaml'
      TimeoutInMinutes: 20
      Parameters:
        pNotifyEmail: !Ref NotificationEmail
        pSupportsGlacier: !FindInMap [ RegionServiceSupport, !Ref 'AWS::Region', Glacier ]
  ProductionVpcTemplate:
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateProductionVPC
    Properties:
      TemplateURL: !Sub '${StackTemplates}/${InfraTemplates}/vpc-production.yaml'
      TimeoutInMinutes: 20
      Parameters:
        pProductionVPCName: !Sub "${ProjectName} Production VPC"
        pRegionAZ1Name: !Ref AvailabilityZone1
        pRegionAZ2Name: !Ref AvailabilityZone2
        pManagementCIDR: !Sub "${ManagementVpcCidrBlock}.0.0/16"
        pProductionCIDR: !Sub "${ProductionVpcCidrBlock}.0.0/16"
        pAppPrivateSubnetACIDR: !Sub "${ProductionVpcCidrBlock}.0.0/20"
        pAppPrivateSubnetBCIDR: !Sub "${ProductionVpcCidrBlock}.16.0/20"
        pDBPrivateSubnetACIDR: !Sub "${ProductionVpcCidrBlock}.32.0/24"
        pDBPrivateSubnetBCIDR: !Sub "${ProductionVpcCidrBlock}.33.0/24"
        pDMZSubnetACIDR: !Sub "${ProductionVpcCidrBlock}.34.0/24"
        pDMZSubnetBCIDR: !Sub "${ProductionVpcCidrBlock}.35.0/24"
        pTemplates: !Sub "${StackTemplates}/${InfraTemplates}"
  StagingVpcTemplate:
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateStagingVPC
    Properties:
      TemplateURL: !Sub '${StackTemplates}/${InfraTemplates}/vpc-production.yaml'
      TimeoutInMinutes: 20
      Parameters:
        pProductionVPCName: !Sub "${ProjectName} Staging VPC"
        pRegionAZ1Name: !Ref AvailabilityZone1
        pRegionAZ2Name: !Ref AvailabilityZone2
        pManagementCIDR: !Sub "${ManagementVpcCidrBlock}.0.0/16"
        pProductionCIDR: !Sub "${StagingVpcCidrBlock}.0.0/16"
        pAppPrivateSubnetACIDR: !Sub "${StagingVpcCidrBlock}.0.0/20"
        pAppPrivateSubnetBCIDR: !Sub "${StagingVpcCidrBlock}.16.0/20"
        pDBPrivateSubnetACIDR: !Sub "${StagingVpcCidrBlock}.32.0/24"
        pDBPrivateSubnetBCIDR: !Sub "${StagingVpcCidrBlock}.33.0/24"
        pDMZSubnetACIDR: !Sub "${StagingVpcCidrBlock}.34.0/24"
        pDMZSubnetBCIDR: !Sub "${StagingVpcCidrBlock}.35.0/24"
        pTemplates: !Sub "${StackTemplates}/${InfraTemplates}"
  TestVpcTemplate:
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateTestVPC
    Properties:
      TemplateURL: !Sub '${StackTemplates}/${InfraTemplates}/vpc-production.yaml'
      TimeoutInMinutes: 20
      Parameters:
        pProductionVPCName: !Sub "${ProjectName} Test VPC"
        pRegionAZ1Name: !Ref AvailabilityZone1
        pRegionAZ2Name: !Ref AvailabilityZone2
        pManagementCIDR: !Sub "${ManagementVpcCidrBlock}.0.0/16"
        pProductionCIDR: !Sub "${TestVpcCidrBlock}.0.0/16"
        pAppPrivateSubnetACIDR: !Sub "${TestVpcCidrBlock}.0.0/20"
        pAppPrivateSubnetBCIDR: !Sub "${TestVpcCidrBlock}.16.0/20"
        pDBPrivateSubnetACIDR: !Sub "${TestVpcCidrBlock}.32.0/24"
        pDBPrivateSubnetBCIDR: !Sub "${TestVpcCidrBlock}.33.0/24"
        pDMZSubnetACIDR: !Sub "${TestVpcCidrBlock}.34.0/24"
        pDMZSubnetBCIDR: !Sub "${TestVpcCidrBlock}.35.0/24"
        pTemplates: !Sub "${StackTemplates}/${InfraTemplates}"
  DevVpcTemplate:
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateDevVPC
    Properties:
      TemplateURL: !Sub '${StackTemplates}/${InfraTemplates}/vpc-production.yaml'
      TimeoutInMinutes: 20
      Parameters:
        pProductionVPCName: !Sub "${ProjectName} Dev VPC"
        pRegionAZ1Name: !Ref AvailabilityZone1
        pRegionAZ2Name: !Ref AvailabilityZone2
        pManagementCIDR: !Sub "${ManagementVpcCidrBlock}.0.0/16"
        pProductionCIDR: !Sub "${DevelopmentVpcCidrBlock}.0.0/16"
        pAppPrivateSubnetACIDR: !Sub "${DevelopmentVpcCidrBlock}.0.0/20"
        pAppPrivateSubnetBCIDR: !Sub "${DevelopmentVpcCidrBlock}.16.0/20"
        pDBPrivateSubnetACIDR: !Sub "${DevelopmentVpcCidrBlock}.32.0/24"
        pDBPrivateSubnetBCIDR: !Sub "${DevelopmentVpcCidrBlock}.33.0/24"
        pDMZSubnetACIDR: !Sub "${DevelopmentVpcCidrBlock}.34.0/24"
        pDMZSubnetBCIDR: !Sub "${DevelopmentVpcCidrBlock}.35.0/24"
        pTemplates: !Sub "${StackTemplates}/${InfraTemplates}"
  ManagementVpcTemplate:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub '${StackTemplates}/${InfraTemplates}/vpc-management.yaml'
      TimeoutInMinutes: 20
      Parameters:
        pProductionCIDR: !If [ CreateProductionVPC, !Sub "${ProductionVpcCidrBlock}.0.0/16", !Ref 'AWS::NoValue' ]
        pProductionVPC: !If [ CreateProductionVPC, !GetAtt ProductionVpcTemplate.Outputs.rVPCProduction, !Ref 'AWS::NoValue' ]
        pRouteTableProdPrivate: !If [ CreateProductionVPC, !GetAtt ProductionVpcTemplate.Outputs.rRouteTableProdPrivate, !Ref 'AWS::NoValue' ]
        pRouteTableProdPublic: !If [ CreateProductionVPC, !GetAtt ProductionVpcTemplate.Outputs.rRouteTableProdPublic, !Ref 'AWS::NoValue' ]
        pStagingCIDR: !If [ CreateStagingVPC, !Sub "${StagingVpcCidrBlock}.0.0/16", !Ref 'AWS::NoValue' ]
        pStagingVPC: !If [ CreateStagingVPC, !GetAtt StagingVpcTemplate.Outputs.rVPCProduction, !Ref 'AWS::NoValue' ]
        pRouteTableStagingPrivate: !If [ CreateStagingVPC, !GetAtt StagingVpcTemplate.Outputs.rRouteTableProdPrivate, !Ref 'AWS::NoValue' ]
        pRouteTableStagingPublic: !If [ CreateStagingVPC, !GetAtt StagingVpcTemplate.Outputs.rRouteTableProdPublic, !Ref 'AWS::NoValue' ]
        pTestCIDR: !If [ CreateTestVPC, !Sub "${TestVpcCidrBlock}.0.0/16", !Ref 'AWS::NoValue' ]
        pTestVPC: !If [ CreateTestVPC, !GetAtt TestVpcTemplate.Outputs.rVPCProduction, !Ref 'AWS::NoValue' ]
        pRouteTableTestPrivate: !If [ CreateTestVPC, !GetAtt TestVpcTemplate.Outputs.rRouteTableProdPrivate, !Ref 'AWS::NoValue' ]
        pRouteTableTestPublic: !If [ CreateTestVPC, !GetAtt TestVpcTemplate.Outputs.rRouteTableProdPublic, !Ref 'AWS::NoValue' ]
        pDevCIDR: !If [ CreateDevVPC, !Sub "${DevelopmentVpcCidrBlock}.0.0/16", !Ref 'AWS::NoValue' ]
        pDevVPC: !If [ CreateDevVPC, !GetAtt DevVpcTemplate.Outputs.rVPCProduction, !Ref 'AWS::NoValue' ]
        pRouteTableDevPrivate: !If [ CreateDevVPC, !GetAtt DevVpcTemplate.Outputs.rRouteTableProdPrivate, !Ref 'AWS::NoValue' ]
        pRouteTableDevPublic: !If [ CreateDevVPC, !GetAtt DevVpcTemplate.Outputs.rRouteTableProdPublic, !Ref 'AWS::NoValue' ]
        pBastionSSHCIDR: !Ref allowedCIDR
        pManagementCIDR: !Sub "${ManagementVpcCidrBlock}.0.0/16"
        pManagementPrivateSubnetACIDR: !Sub "${ManagementVpcCidrBlock}.0.0/20"
        pManagementPrivateSubnetBCIDR: !Sub "${ManagementVpcCidrBlock}.16.0/20"
        pManagementDMZSubnetACIDR: !Sub "${ManagementVpcCidrBlock}.34.0/24"
        pManagementDMZSubnetBCIDR: !Sub "${ManagementVpcCidrBlock}.35.0/24"
        pManagementVPCName: !Sub "${ProjectName} Management VPC"
        pEC2KeyPairBastion: !Ref pEC2KeyPairBastion
        pEC2KeyPair: !Ref pEC2KeyPair
        pBastionAmi: !FindInMap [ AWSAMIRegionMap, !Ref 'AWS::Region', AMZNLINUXHVM ]
        pRegionAZ1Name: !Ref AvailabilityZone1
        pRegionAZ2Name: !Ref AvailabilityZone2
        pBastionInstanceType: t2.small
        pSupportsNatGateway: !FindInMap [ RegionServiceSupport, !Ref 'AWS::Region', NatGateway ]
        pNatAmi: !FindInMap [ AWSAMIRegionMap, !Ref 'AWS::Region', AMZNLINUXHVM ]
        pNatInstanceType: !FindInMap [ AWSAMIRegionMap, !Ref 'AWS::Region', InstanceType ]
Mappings:
  RegionServiceSupport:
    us-east-1:
      ConfigRules: true
      NatGateway: true
      Glacier: true
    us-east-2:
      ConfigRules: true
      NatGateway: true
      Glacier: true
    us-west-1:
      ConfigRules: true
      NatGateway: true
      Glacier: true
    us-west-2:
      ConfigRules: true
      NatGateway: true
      Glacier: true
    ca-central-1:
      ConfigRules: false
      NatGateway: true
      Glacier: true
    eu-central-1:
      NatGateway: true
      ConfigRules: true
      Glacier: true
    eu-west-1:
      ConfigRules: true
      NatGateway: true
      Glacier: true
    eu-west-2:
      ConfigRules: false
      NatGateway: true
      Glacier: true
    ap-northeast-1:
      ConfigRules: true
      NatGateway: true
      Glacier: true
    ap-northeast-2:
      ConfigRules: true
      NatGateway: true
      Glacier: true
    ap-south-1:
      ConfigRules: false
      NatGateway: true
      Glacier: true
    ap-southeast-1:
      ConfigRules: true
      NatGateway: true
      Glacier: false
    ap-southeast-2:
      ConfigRules: true
      NatGateway: true
      Glacier: true
    sa-east-1:
      ConfigRules: false
      NatGateway: true
      Glacier: false
    us-gov-west-1:
      ConfigRules: false
      NatGateway: false
      Glacier: false
  AWSInfoRegionMap:
    ap-northeast-1:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    ap-northeast-2:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    ap-south-1:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    ap-southeast-1:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    ap-southeast-2:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    ca-central-1:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    eu-central-1:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    eu-west-1:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    eu-west-2:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    sa-east-1:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    us-east-1:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    us-east-2:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    us-gov-west-1:
      Partition: aws-us-gov
      QuickStartS3URL: https://s3-us-gov-west-1.amazonaws.com
    us-west-1:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
    us-west-2:
      Partition: aws
      QuickStartS3URL: https://s3.amazonaws.com
  CustomVariables:
    vResourceEnvironmentTagKey:
      Value: Environment
    vResourceEnvironmentTagValue:
      Value: development
  AWSAMIRegionMap:
    AMI:
      AMZNLINUXHVM: amzn-ami-hvm-2017.03.1.20170623-x86_64-gp2
    ap-northeast-1:
      AMZNLINUXHVM: ami-3bd3c45c
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    ap-northeast-2:
      AMZNLINUXHVM: ami-e21cc38c
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    ap-south-1:
      AMZNLINUXHVM: ami-47205e28
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    ap-southeast-1:
      AMZNLINUXHVM: ami-77af2014
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    ap-southeast-2:
      AMZNLINUXHVM: ami-10918173
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    ca-central-1:
      AMZNLINUXHVM: ami-a7aa15c3
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    eu-central-1:
      AMZNLINUXHVM: ami-82be18ed
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    eu-west-1:
      AMZNLINUXHVM: ami-d7b9a2b1
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    eu-west-2:
      AMZNLINUXHVM: ami-ed100689
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    sa-east-1:
      AMZNLINUXHVM: ami-87dab1eb
      InstanceType: m4.large
      InstanceTypeDatabase: db.m3.large
    us-east-1:
      AMZNLINUXHVM: ami-a4c7edb2
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    us-east-2:
      AMZNLINUXHVM: ami-8a7859ef
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    us-gov-west-1:
      AMZNLINUXHVM: ami-ffa61d9e
      InstanceType: m4.large
      InstanceTypeDatabase: db.m3.large
    us-west-1:
      AMZNLINUXHVM: ami-327f5352
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
    us-west-2:
      AMZNLINUXHVM: ami-6df1e514
      InstanceType: m4.large
      InstanceTypeDatabase: db.m4.large
Outputs:
  AmznLinuxHvmAMI:
    Description: Amazon Linux AMI
    Value: !FindInMap [ AWSAMIRegionMap, !Ref 'AWS::Region', AMZNLINUXHVM ]
  CfnStacksId:
    Description: cfn-stacks.com artifact id
    Value: @artifactId@
  CfnStacksVersion:
    Description: cfn-stacks.com artifact version
    Value: v@version@

  CfnStacksIdProductionVpcTemplate:
    Condition: CreateProductionVPC
    Value: !GetAtt ProductionVpcTemplate.Outputs.CfnStacksId
  CfnStacksVersionProductionVpcTemplate:
    Condition: CreateProductionVPC
    Value: !GetAtt ProductionVpcTemplate.Outputs.CfnStacksVersion
  ProductionVpc:
    Condition: CreateProductionVPC
    Value: !GetAtt ProductionVpcTemplate.Outputs.rVPCProduction
  ProductionVpcCidrBlock:
    Condition: CreateProductionVPC
    Value: !Sub '${ProductionVpcCidrBlock}.0.0/16'
  ProductionDmzSubnet1:
    Condition: CreateProductionVPC
    Value: !GetAtt ProductionVpcTemplate.Outputs.rDMZSubnetA
  ProductionDmzSubnet2:
    Condition: CreateProductionVPC
    Value: !GetAtt ProductionVpcTemplate.Outputs.rDMZSubnetB
  ProductionPrivateSubnet1:
    Condition: CreateProductionVPC
    Value: !GetAtt ProductionVpcTemplate.Outputs.rAppPrivateSubnetA
  ProductionPrivateSubnet2:
    Condition: CreateProductionVPC
    Value: !GetAtt ProductionVpcTemplate.Outputs.rAppPrivateSubnetB

  CfnStacksIdStagingVpcTemplate:
    Condition: CreateStagingVPC
    Value: !GetAtt StagingVpcTemplate.Outputs.CfnStacksId
  CfnStacksVersionStagingVpcTemplate:
    Condition: CreateStagingVPC
    Value: !GetAtt StagingVpcTemplate.Outputs.CfnStacksVersion
  StagingVpc:
    Condition: CreateStagingVPC
    Value: !GetAtt StagingVpcTemplate.Outputs.rVPCProduction
  StagingVpcCidrBlock:
    Condition: CreateStagingVPC
    Value: !Sub '${StagingVpcCidrBlock}.0.0/16'
  StagingDmzSubnet1:
    Condition: CreateStagingVPC
    Value: !GetAtt StagingVpcTemplate.Outputs.rDMZSubnetA
  StagingDmzSubnet2:
    Condition: CreateStagingVPC
    Value: !GetAtt StagingVpcTemplate.Outputs.rDMZSubnetB
  StagingPrivateSubnet1:
    Condition: CreateStagingVPC
    Value: !GetAtt StagingVpcTemplate.Outputs.rAppPrivateSubnetA
  StagingPrivateSubnet2:
    Condition: CreateStagingVPC
    Value: !GetAtt StagingVpcTemplate.Outputs.rAppPrivateSubnetB

  CfnStacksIdTestVpcTemplate:
    Condition: CreateTestVPC
    Value: !GetAtt TestVpcTemplate.Outputs.CfnStacksId
  CfnStacksVersionTestVpcTemplate:
    Condition: CreateTestVPC
    Value: !GetAtt TestVpcTemplate.Outputs.CfnStacksVersion
  TestVpc:
    Condition: CreateTestVPC
    Value: !GetAtt TestVpcTemplate.Outputs.rVPCProduction
  TestVpcCidrBlock:
    Condition: CreateTestVPC
    Value: !Sub '${TestVpcCidrBlock}.0.0/16'
  TestDmzSubnet1:
    Condition: CreateTestVPC
    Value: !GetAtt TestVpcTemplate.Outputs.rDMZSubnetA
  TestDmzSubnet2:
    Condition: CreateTestVPC
    Value: !GetAtt TestVpcTemplate.Outputs.rDMZSubnetB
  TestPrivateSubnet1:
    Condition: CreateTestVPC
    Value: !GetAtt TestVpcTemplate.Outputs.rAppPrivateSubnetA
  TestPrivateSubnet2:
    Condition: CreateTestVPC
    Value: !GetAtt TestVpcTemplate.Outputs.rAppPrivateSubnetB

  CfnStacksIdDevVpcTemplate:
    Condition: CreateDevVPC
    Value: !GetAtt DevVpcTemplate.Outputs.CfnStacksId
  CfnStacksVersionDevVpcTemplate:
    Condition: CreateDevVPC
    Value: !GetAtt DevVpcTemplate.Outputs.CfnStacksVersion
  DevVpc:
    Condition: CreateDevVPC
    Value: !GetAtt DevVpcTemplate.Outputs.rVPCProduction
  DevVpcCidrBlock:
    Condition: CreateDevVPC
    Value: !Sub '${DevelopmentVpcCidrBlock}.0.0/16'
  DevDmzSubnet1:
    Condition: CreateDevVPC
    Value: !GetAtt DevVpcTemplate.Outputs.rDMZSubnetA
  DevDmzSubnet2:
    Condition: CreateDevVPC
    Value: !GetAtt DevVpcTemplate.Outputs.rDMZSubnetB
  DevPrivateSubnet1:
    Condition: CreateDevVPC
    Value: !GetAtt DevVpcTemplate.Outputs.rAppPrivateSubnetA
  DevPrivateSubnet2:
    Condition: CreateDevVPC
    Value: !GetAtt DevVpcTemplate.Outputs.rAppPrivateSubnetB